### ISSUE TITLE
Text on Pastenym disappeared

### ISSUE THREAD

**Issue by Endo-Heikichi** [notrustverify/pastenym#27]
This Pastenym is about 4 days old and I noticed that it no longer has the content that I had saved on it. It simply says, "text not found". 

I didn't save anything critical on it. But since I saw the bug, I thought I should report it.

https://pastenym.ch/#/9tNDPb-d&key=c29946c21838d7668fb55bd1de822584

**Comment by sven-hash** [comment]
Thanks for this.

Yes we had a bug when deploying a new version with the DB, we will look fo the future update to limit this kind of problem
