### ISSUE TITLE
Ability to set a password to protect the paste

### ISSUE THREAD

**Issue by phil71x** [notrustverify/pastenym#28]
Self explanatory.

Similar to Bitwarden Send : https://bitwarden.com/products/send/

**Comment by sven-hash** [comment]
You want to have the ability to set a password in addition of the key used to encrypt the paste ?

**Comment by sven-hash** [comment]
Here's how you can do it, just copy the link and send it without the key, pass the key via another channel

Just click on "or separately" after the url id was received

![](https://i.imgur.com/tcgIJNC.png)

**Comment by amadeous** [comment]
@phil71x, does the current client side encryption feature, as shown by @sven-hash, matches your feature request?
Can we close this issue?

**Comment by phil71x** [comment]
Yes @amadeous. And passwords are so has-been anyway!
