### ISSUE TITLE
Support POSTing content

### ISSUE THREAD

**Issue by rpdelaney** [notrustverify/pastenym#32]
As seen on sites such as paste.rs and others:

```console
$ echo "hello" | curl -Ss --data-binary @- https://paste.rs
```

I understand that you have a cli utility, but I would prefer not to install binaries when I have trusted HTTPS tools already.

**Comment by sven-hash** [comment]
I totally understand your request, unfortunately to access and use the mixnet you need a client that can "talk nym", this is why we dev a cli-client to offer people the possibility to interact with cli and pipe is supported

We are going to work on a Rust cli client to not have to start a nym-client aside, in the mean time you will find everything [here](https://github.com/notrustverify/pastenym-cli/releases)
